#!/usr/bin/perl -w

# The MIT License
#
# Copyright (c) 2014 Adrian Tan <atks@umich.edu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

use strict;
use warnings;

my $executablePath = __FILE__;
$executablePath =~ s/[^\/]+$//;
my $defaultUser = "atks";
my $configFile = $executablePath . ".config";
if (-e $configFile)
{
    open(IN, $configFile) || die "Cannot open config file";
    $defaultUser = <IN>;
    chomp($defaultUser);
    close(IN);
}
else
{
    print STDERR "Please create a .config file containing your user name in the directory of cluster tools.\n";
    exit(1);
}

my $usr;
my $target_usr;

if (@ARGV==0)
{
    $usr = $defaultUser;
    $target_usr = $defaultUser;
}
elsif (@ARGV==1)
{
    $usr = $defaultUser;
    $target_usr = $ARGV[0];
}

my $host = `hostname`;
my @gateways = ();
if ($host =~ /(fantasia|wonderland|snowwhite|dumbo)/)
{
    @gateways = ("fantasia", "wonderland", "snowwhite", "dumbo", "slurm");
}
else
{
    chomp($host);
    push(@gateways, $host);
}

my %TNODE = ();
my %LOG = ();
my %ULOG = ();
open(IN, $executablePath . "good_node_list.txt");
while(<IN>)
{
    chomp;
    my ($node, $newNode) = split("\t");
    $TNODE{$newNode} = $node;
    $LOG{$node} = 0;
    $ULOG{$node} = 0;
}
close(IN);

my $total = 0;
my $userTotal = 0;

#count jobs
for my $gateway (@gateways)
{
    my $cmd;
    my $c;
    if ($gateway =~ /(fantasia|wonderland|snowwhite|dumbo)/)
    {
        if ($host eq $gateway)
        {
            $cmd = "mosps -eu | tail -n +2"
        }
        else
        {
            $cmd = "ssh $usr@" . $gateway . " 'mosps -eu | tail -n +2'";
        }
        
        $c = `$cmd`;
        
#        $cmd = "ssh $usr@" . "sardinia 'mosps -eu | tail -n +2'";
#        my $c1 = `$cmd`;
#        $c .= "\n$c1";
#        
#        $cmd = "ssh $usr@" . "bipolar 'mosps -eu | tail -n +2'";
#        $c1 = `$cmd`;
#        $c .= "\n$c1";
#        
#        $cmd = "ssh $usr@" . "esp 'mosps -eu | tail -n +2'";
#        $c1 = `$cmd`;
#        $c .= "\n$c1";        
    }
    elsif ($gateway eq "slurm")
    {
        $cmd = "squeue | tail -n +2 | tr -s ' ' '\\t'  | cut -f5,9,2 | perl -lane '{print \"\$F[1]\\t\$F[0]\\t\$F[2]\"}'";
        $c = `$cmd`;
    }
    elsif ($gateway =~ /(1000g|got2d|amd|psoriasis|topmed)/)
    {
        $cmd = "squeue | grep $gateway | tr -s ' ' '\\t'  | cut -f3,5,9 ";
        $c = `$cmd`;
    }
    elsif ($gateway =~ /(sardinia|esp)/)
    {
        $cmd = "mosps -eu | tail -n +2";
        my $c1 = `$cmd`;
        $cmd = "squeue | grep $gateway | tr -s ' ' '\\t'  | cut -f3,5,9 ";
        my $c2 = `$cmd`;

        $c = "$c1\n$c2";
    }
   
    my @jobs = split("\n", $c);
    for my $job (@jobs)
    {
        my ($cluster, $user, $node,  $rest) = split(/\s+/, $job);
        next if ($node =~ /wait|here/);

        if ($gateway eq "slurm")
        {
            if (!exists($TNODE{$node}))
            {
                print STDERR "adding $node\n";
                
                if ($node=~/-mc\d\d/)
                {
                    $TNODE{$node} = $node;
                }
                elsif ($node=~/r\d\d\d\d/)
                {
                    $TNODE{$node} = $node;
                }
                elsif ($node=~/topmed/)
                {
                    $TNODE{$node} = $node;
                }
                elsif ($node=~/\(.+\)/)
                {
                    $TNODE{$node} = $node;
                }
                else
                {
                    my $cmd1 = "ssh $usr\@" . "fantasia \"mosctl whois $node\"";
                    print $cmd1 . "\n";
                    my $newNode = `$cmd1`;

                    if ($newNode eq "")
                    {
                        $newNode = $node;
                    }
                    $TNODE{$node} = $newNode;
                    $node = $newNode;
                }
            }
            else
            {
                $node = $TNODE{$node};
            }
        }

        if (!exists($LOG{$node}))
        {
            $LOG{$node} = 0;
            $ULOG{$node} = 0;
        }

        if ($user eq $target_usr)
        {
            ++$ULOG{$node};
            ++$userTotal;
        }

        ++$LOG{$node};
        ++$total;
    }
}

$host =~ s/^\s+//;
$host =~ s/\s+$//;

print "\n\t$host\n";
print "\t" . ("=" x length($host)) . "\n";
if ($host =~ /(fantasia|wonderland|snowwhite|dumbo)/)
{
    printf("\t%25s    usr(sum)   %25s    usr(sum)   %25s    usr(sum)\n", "node", "node", "node");
    my $i = 0;
    for my $node (sort {$LOG{$b} <=> $LOG{$a}} keys(%LOG))
    {
        print "\n" if ($i!=0 && $i%3==0);
        printf("\t%25s  %4d(%4d)", $node, $ULOG{$node}, $LOG{$node});

        ++$i;
    }
    print "\n\n";
    printf("\t%8s: %d jobs\n", $target_usr, $userTotal);
    printf("\t   total: %4d jobs\n\n", $total);
}
else
{
    print "\tnode  usr(sum)\n";
    for my $node (sort {$a cmp $b} keys(%LOG))
    {
        if ($ULOG{$node}!=0 || $node=~/$host/)
        {
            printf("\t%4s  %3d(%3d)\n", $node, $ULOG{$node}, $LOG{$node});
        }
    }
    print "\n";
    printf("\t%8s: %4d jobs\n", $target_usr, $userTotal);
    printf("\t   total: %4d jobs\n\n", $total);
}
