#!/usr/bin/perl -w
use strict;
use warnings;

my $acct = @ARGV==1 ? $ARGV[0] : "atks";

my %LOG;

my @nodes = split(",", "10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171");

my $host = `hostname`;

open(OUT, ">good_node_list.txt") || die "Cannot open good_node_list.txt";

for my $node (@nodes)
{
    my $cmd = "";
    my $newNode = "";
        
    if ($host =~/fantasia|wonderland|snowwhite/)
    {
        $cmd = "mosctl whois $node";
        $newNode = `$cmd`;
    }
    else
    {
        $cmd = "ssh $acct\@" . "fantasia \"mosctl whois $node\"";
        $newNode = `$cmd`;
    }
    
    $newNode =~ /\(([^\)]+)\.csgstat\.sph\.umich\.edu\)/;
    
    
    print OUT "$node\t$1\n";
}

close(OUT);
